version: '3'
networks:
    store:

services:
    test-postgres:
        env_file:
            - .env
        container_name: ${DB_HOST}
        hostname: ${DB_HOST}
        image: postgres:12.4-alpine
        environment:
            PGDATA: /var/lib/postgresql/data
            APPDATA: /var/lib/postgresql/data
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}
        ports:
            - ${DB_PORT}:${DB_PORT}
        volumes:
            - ./postgres:/var/lib/postgresql/data
        networks:
            - store

    test-back:
        env_file:
            - .env
        container_name: ${BACK_APP_NAME}
        hostname: ${BACK_APP_HOST}
        image: node:14.15.4-alpine3.11
        ports:
            - ${BACK_APP_PORT}:${BACK_APP_PORT}
        volumes:
            - ./:/app
        command: npm run start:dev
        working_dir: /app
        depends_on: 
            - test-postgres
        networks:
            - store